let profilesection=document.querySelector('.profile-section');
let heading=document.createElement('h4');
let text=document.createTextNode('This heading is generated by dom');
heading.appendChild(text);
profilesection.appendChild(heading);
let listitem=document.querySelectorAll('.list-item:nth-child(odd)');
listitem.forEach(li=>{
    li.style='color:red';
    li.textContent='not a car'
});

let subheading=document.querySelector('h4');
subheading.textContent='Car Profile';